# Generated by Django 5.0.4 on 2024-06-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proyecto_name', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='NOMBRE PROYECTO')),
                ('proyecto_student', models.CharField(max_length=80, verbose_name='Estudiante')),
                ('proyecto_topic', models.CharField(choices=[('0', 'sugerencia'), ('1', 'consulta'), ('2', 'oferta laboral'), ('3', 'oferta práctica')], max_length=20, verbose_name='TEMA')),
                ('proyecto_patrocinador', models.CharField(max_length=80, verbose_name='PROFESOR')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
