# Generated by Django 5.0.4 on 2024-06-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='proyecto_topic',
            field=models.CharField(choices=[('0', 'tipo A'), ('1', 'tipo B'), ('2', 'tipo C'), ('3', 'tipo D')], max_length=20, verbose_name='TEMA'),
        ),
    ]
